#!/bin/sh

if [[ `whoami` != root ]]; then
  echo Attention: this profile should be run as root.
  exit 3
fi

if [ ! -e config ]; then
  echo Attention: You must create a config directory (or link).
fi

umask 022
/usr/bin/nALFS -l -L nalfs.log LFS.xml
