#!/bin/bash
###############################################################################
#                                                                             #
# File:        entResolver                                                    #
#                                                                             #
# Description: Works around libxml2 bug 135713 by preprocessing entity        #
#              references before performing any stylesheet processing.        #
#                                                                             #
# Author:      Manuel Canales Esparcia                                        #
#                                                                             #
###############################################################################

NAME=`basename "$0"`
DESTDIR="$1"

cd $DESTDIR

if [ -z "$1" ]; then
        echo "USAGE: $NAME destdir"
        exit
fi

for i in `find . -name "*.xml"`; do
        xmllint --nonet --noent "${i}" > "${i}";
done

exit 0

