#!/bin/bash

# Bootstrap script for nALFS, used to get a CVS checkout ready for use.

[ -r src/nalfs.c ] || {
    echo "***"
    echo "*** The bootstrap script must be run in the top directory"
    echo "*** of the CVS source distribution."
    echo "***"
    exit 1
}

[ -d gnubuild ] || mkdir gnubuild

cat > Makefile.am <<EOF
EXTRA_DIST = CHANGES COPYING README CREDITS
EXTRA_DIST += scripts/flog
# autoconf/automake do not currently offer a way to avoid installing
# the static libraries produced when the user chooses --disable-shared
# (or when the platform does not support shared libraries), so force
# them to be immediately removed after installation until a better
# solution can be found; same is needed for include files
install-exec-hook:
if STATIC_BUILD
	rm -rf \$(pkglibdir)
	rm -f \$(libdir)/libnALFS.*
endif

install-data-hook:
if STATIC_BUILD
	rm -f \$(includedir)/nALFS.h
endif

AM_CPPFLAGS = -I\$(srcdir)/src/include -I\$(srcdir)/src
AM_CFLAGS = -Werror
bin_PROGRAMS = src/nALFS
src_nALFS_LDFLAGS = -dlopen self
src_nALFS_CPPFLAGS = \$(XML2_INCLUDES) \$(AM_CPPFLAGS)
src_nALFS_LDADD = \$(XML2_LIB) \$(CURL_LIB) \$(SSL_LIB) src/lib/libnALFS.la
src_nALFS_LDADD += \$(LIBADD_DL) \$(MAIN_LIBS)
if !STATIC_BUILD
src_nALFS_CPPFLAGS += -DHANDLERS_DIRECTORY=\"\$(pkglibdir)\"
else
src_nALFS_LDFLAGS += -all-static
endif
src_nALFS_SOURCES =
EOF

for file in src/*.{c,h}; do
    echo src_nALFS_SOURCES += ${file} >> Makefile.am
done

for file in src/handlers/*.c; do
cat >> Makefile.am <<EOF
src_nALFS_LDFLAGS += -dlopen ${file%.c}.la
EOF
done

cat >> Makefile.am <<EOF
include_HEADERS = src/include/nALFS.h
EOF

cat >> Makefile.am <<EOF
lib_LTLIBRARIES = src/lib/libnALFS.la
src_lib_libnALFS_la_LDFLAGS = -avoid-version
src_lib_libnALFS_la_CPPFLAGS = \$(SSL_INCLUDES) \$(CURL_INCLUDES) \$(AM_CPPFLAGS)
src_lib_libnALFS_la_LIBADD = \$(CURL_LIB) \$(SSL_LIB)
src_lib_libnALFS_la_SOURCES =
EOF

for file in src/lib/*.{c,h}; do
    echo src_lib_libnALFS_la_SOURCES += ${file} >> Makefile.am
done

cat >> Makefile.am <<EOF
pkglib_LTLIBRARIES =
EOF

for file in src/handlers/*.c; do
    am_file=${file%.c}
    am_file=${am_file//\//_}
    cat >> Makefile.am <<EOF
pkglib_LTLIBRARIES += ${file%.c}.la
${am_file}_la_SOURCES = ${file}
${am_file}_la_LDFLAGS = -module -avoid-version
EOF
done

autoreconf --install --force

# libtool supports a --silent argument, but does not pass it to
# itself when it is reinvoked at the end of --mode=install processing
# this patch corrects that behavior to keep the "noise" down
# during installation
patch -d gnubuild -p1 <<EOF
--- libtool-1.5/ltmain.sh~	Mon Apr 14 14:58:24 2003
+++ libtool-1.5/ltmain.sh	Thu Oct 16 09:02:56 2003
@@ -238,6 +238,7 @@
   --debug)
     \$echo "\$progname: enabling shell trace mode"
     set -x
+    preserve_args="\$preserve_args \$arg"
     ;;
 
   --dry-run | -n)
@@ -268,6 +269,7 @@
 
   --quiet | --silent)
     show=:
+    preserve_args="\$preserve_args \$arg"
     ;;
 
   --tag) prevopt="--tag" prev=tag ;;
@@ -5653,7 +5655,7 @@
     if test -n "\$current_libdirs"; then
       # Maybe just do a dry run.
       test -n "\$run" && current_libdirs=" -n\$current_libdirs"
-      exec_cmd='\$SHELL \$0 --finish\$current_libdirs'
+      exec_cmd='\$SHELL \$0 \$preserve_args --finish\$current_libdirs'
     else
       exit 0
     fi

EOF
