#!/bin/bash

# Bootstrap script for nALFS, used to get a CVS checkout ready for use.

[ -r src/nalfs.c ] || {
    echo "***"
    echo "*** The bootstrap script must be run in the top directory"
    echo "*** of the CVS source distribution."
    echo "***"
    exit 1
}

# some 'macros' for processing filename lists
SP2NL="tr '\040' '\012'"
NL2SP="tr '\015\012' '\040\040'"

# create a directory for the GNU autotools to put their stuff into
[ -d gnubuild ] || mkdir gnubuild
# create nALFS-config.in to quiet autoconf, which will overwrite it later
touch nALFS-config.in

# build available handler list
# grep each handler file to determine which syntax version(s) it supports
# store this in a variable for each handler, so bootstrap.configure can use it
# this will result in a Makefile that builds only the
# handlers containing versions the user requests with --enable-syntax
# also generate a list of all syntax versions present across all handlers

all_handlers=`ls src/handlers/*.c | sed 's~src/handlers/\(.*\)\.c~\1~'`
for handler in ${all_handlers}; do
    syntaxes=`grep HANDLER_SYNTAX src/handlers/${handler}.c | sed 's/^.*HANDLER_SYNTAX_\(.*\)$/\1/' | sort -u`
    eval "${handler}_syntaxes=\"${syntaxes}\""
    all_syntaxes="${all_syntaxes} ${syntaxes}"
done
all_syntaxes=`echo ${all_syntaxes} | ${SP2NL} | sort -u`

. ./bootstrap.Makefile > Makefile.am

. ./bootstrap.configure > configure.ac

autoreconf --install --force

. ./bootstrap.libtool
