CFLAGS=-I../libalfs -I..

LIBS=ass.so book.so nalfs.so syn.so

all: $(LIBS)

include ../inc.mak

ass.so: ../libalfs/libalfs.a
book.so: ../libalfs/libalfs.a
nalfs.so: ../libalfs/libalfs.a
syn.so: ../libalfs/libalfs.a
