CFLAGS=-I../libalfs -I..

LIBS=ass.so blfs.so book.so nalfs.so rng.so syn.so
#LIBS+=sample.so

all: $(LIBS)

include ../inc.mak

ass.so: ../libalfs/libalfs.a
blfs.so: ../libalfs/libalfs.a
book.so: ../libalfs/libalfs.a
nalfs.so: ../libalfs/libalfs.a
rng.so: ../libalfs/libalfs.a
syn.so: ../libalfs/libalfs.a
